### ISSUE TITLE
What the command?

### ISSUE THREAD

**Issue by ItzFel** [hachkingtohach1/Duels#3]

**Comment by hachkingtohach1** [comment]
you can read guild.txt

**Comment by ItzFel** [comment]
![Screenshot_2021-01-25-09-59-21-458_turbo client](https://user-images.githubusercontent.com/62336632/105652417-23c3d580-5ef4-11eb-8f35-886b044cb25a.png)
![Screenshot_2021-01-25-09-59-40-654_turbo client](https://user-images.githubusercontent.com/62336632/105652428-2d4d3d80-5ef4-11eb-9836-0b8379efa22d.png)


Like this?
